### ISSUE TITLE
The Crystal biome spawns too high for crystal trees to spawn

### ISSUE THREAD

**Issue by WenXin20** [Mowmaster/Dust#9]
Forge v14.23.5.2810-1.12.2
Dust v0.0003.5
[Space Age](https://minecraft.curseforge.com/projects/the-space-age-mod) v1.5.1-beta

I noticed that the crystal biome can go as high as y = 255, blocks can't be placed above this height and the crystal trees can't spawn. 

Going to that height also teleports the player to the space dimension from the Space Age mod, which makes it next to impossible to cross this biome. 

Perhaps a config for biome heights?

**Comment by Mowmaster** [comment]
If you would like to discuss this in length, i have a discord you can join: https://discord.gg/vfDPUv
I will install these mods and test for myself as well.

**Comment by WenXin20** [comment]
Thanks for looking into it, but I don't have a discord and I have to head to work soon. But thanks!

**Comment by Mowmaster** [comment]
alright thats fine, i might have to install natures compass mod too, having trouble finding my own biome xD

**Comment by WenXin20** [comment]
I could send a picture if that would help.

**Comment by Mowmaster** [comment]
please do

**Comment by Mowmaster** [comment]
Okay well from what ive encountered so far, as far as being really high, and going into orbit, thats a space age thing. The crystal biome can generate up to max height but only at its highest peaks, if a player is flying high enough where to go over the highest part thats on them, they might as well just made a dirt pillar to fly over at that point, and sure in some cases you could scale a mountain and could maybe go high enough to be an issue, but again i feel like thats the players doing on purpose in this case.

as for trees being cut off by the build limit thats on me for the world gen part, for now im not going to worry too much about it since there is a much needed worldgen update in the works for after 1.13 forge releases a stable build.

Lastly i will add a biome configuration in the config just for the sake of things since i know not everyone likes the huge biomes, ill close this issue with that commit and the feature will come out in the next build, which is probably my tier 0 machine and structure update.

**Comment by WenXin20** [comment]
Yep, that's what happened to me. I was flying over the biome in creative. 
And, thanks!

**Comment by Mowmaster** [comment]
Closing due to the discontinued development of the 1.12 version
